#!/usr/bin/env bash
# Sync files by using rclone

source $ME_UTIL
RCLONE_LOG=${ME_LOG_DIR}/rclone.log
RCLONE_CFG_DIR=${ME_ETC_DIR}/me-rclone


usage() {
  cat <<EOF
  Usage: me-rclone [<options>]

  Options:
    -l, --list                List all confs
    -c, --check               Read specified confs and check
    -u, --upload              Read specified confs and upload
    -d, --download            Read specified confs and download
    -n, --new-conf            Create a new conf
    -v, --view-conf           Display content of a specified conf
    -e, --edit-conf <conf>    Modify a conf
    -d, --delete-conf <conf>  Delete a conf
    --view-log                Display content of log
EOF
}

list() {
  find "$RCLONE_CFG_DIR" \
    -type f \
    -name '*.conf' \
    ! -name 'example.conf' \
    -exec basename -s .conf {} \;
}

execute() {
  local mode=$1

  [[ ! $mode =~ ^download$|^upload$|^check$ ]] && 
    _me_die "$ME_ES_UNKNOWN_ARGUMENT" "Unknown argument <mode>."
  [[ -z "${*:2}" ]] && 
    _me_die "$ME_ES_UNKNOWN_ARGUMENT" "Missing argument <conf>."

  local cfg_path

  for cfg in "${@:2}"; do
    cfg_path=$RCLONE_CFG_DIR/$cfg.conf

    if [[ ! -f $cfg_path ]]; then
      _me_warn "Unknown '$cfg'."
      continue
    fi

    unset LOCAL REMOTE from to
    source "$cfg_path"
    [[ -z $LOCAL ]] &&
      _me_die "$ME_ES_FAILURE" "Empyt value 'LOCAL' found in '$cfg.conf'."
    [[ -z $REMOTE ]] &&
      _me_die "$ME_ES_FAILURE" "Empty value 'REMOTE' found in '$cfg.conf'."

    if [[ $mode == check ]]; then
      local method=check from=$LOCAL to=$REMOTE
    elif [[ $mode == upload ]]; then
      local method=copy from=$LOCAL to=$REMOTE
    elif [[ $mode == download ]]; then
      local method=copy from=$REMOTE to=$LOCAL
    fi

    # When notify-send is run in cron job, The DBUS_SESSION_BUS_ADDRESS
    # variable must be set correctly.
    export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
    { 
      date=$(date)
      _me_info $date
      _me_info "Run 'rconle $method $from $to'"

      if rclone "$method" -P "$from" "$to"; then
        notify-send \
          -u low -a me-rclone \
          "$date" "Succeed to run:\n  'rclone $method $from $to'"
      else
        notify-send \
          -u critical -a me-rclone \
          "$date" "Error occurs.\nSee file://${RCLONE_LOG}"
      fi

      echo -e "\n\n"
    } 2>&1 | tee -a "$RCLONE_LOG"

  done
}

configure() {
  local mode=$1 cfg=$2
  local cfg_path sure
  local temp=$(mktemp) editor=${EDITOR:-nano}

  # Delete mode
  if [[ $mode == delete ]]; then
    cfg_path=$RCLONE_CFG_DIR/$cfg.conf
    [[ -z $cfg ]] &&
      _me_die "$ME_ES_UNKNOWN_ARGUMENT" "Missing argument <conf>."
    [[ ! -f $cfg_path ]] &&
      _me_die "$ME_ES_FAILURE" "Conf '$cfg' doesn't exist."
    rm "$cfg_path" && _me_info "Succeed to remove '$cfg_path'."
    exit 0

  # New mode
  elif [[ $mode == new ]]; then
    read -p "Your configuration name: " cfg
    cfg_path=$RCLONE_CFG_DIR/$cfg.conf
    [[ -f $cfg_path ]] &&
      _me_die "$ME_ES_FAILURE" "Conf '$cfg' has already been existed."
    cp -f "$RCLONE_CFG_DIR/example.conf" "$temp"

  # View mode
  elif [[ $mode == view ]]; then
    cfg_path=$RCLONE_CFG_DIR/$cfg.conf
    [[ -z $cfg ]] &&
      _me_die "$ME_ES_UNKNOWN_ARGUMENT" "Missing argument <conf>."
    [[ ! -f $cfg_path ]] &&
      _me_die "$ME_ES_FAILURE" "Conf "$cfg" doesn't exist."
    cat "$cfg_path"
    exit 0

  # Edit mode
  elif [[ $mode == edit ]]; then
    cfg_path=$RCLONE_CFG_DIR/$cfg.conf
    [[ -z $cfg ]] &&
      _me_die "$ME_ES_UNKNOWN_ARGUMENT" "Missing argument <conf>."
    [[ ! -f $cfg_path ]] &&
      _me_die "$ME_ES_FAILURE" "Conf '$cfg' doesn't exist."
    cp -f "$cfg_path" "$temp"

  # Unknown mode
  else
    _me_die "$ME_ES_UNKNOWN_ARGUMENT" "Unknown argument <mode>."
  fi

  "$editor" "$temp"

  # Save modification
  [[ $mode == new ]] && local create=create || local create=update
  for ((;;)) ; do
    read -p "Are you sure? [y/n]: " sure
    if [[ $sure =~ [Yy] ]]; then
      mv "$temp" "$cfg_path" && _me_info "Succeed to $create '$cfg_path'."
      break
    elif [[ $sure =~ [Nn] ]]; then
      _me_warn "Ignore your modification."
      break
    fi
  done
}


# main
case $1 in
  -l|--list        ) list ;;
  -c|--check       ) shift; execute check "$@" ;;
  -u|--upload      ) shift; execute upload "$@" ;;
  -d|--download    ) shift; execute download "$@" ;;
  -n|--new-conf    ) configure new ;;
  -v|--view-conf   ) configure view "$2" ;;
  -e|--edit-conf   ) configure edit "$2" ;;
  --delete-conf    ) configure delete "$2" ;;
  --view-log       ) less -R "$RCLONE_LOG" ;;
  *                ) usage ;;
esac
