#!/usr/bin/env bash

set -e

current_commit=$(git rev-parse HEAD)
initial_commit=$(git rev-list --max-parents=0 HEAD)
if [[ ${current_commit} == ${initial_commit} ]]; then
  echo "alread in initial commit"
elif (( $(git rev-list --reverse --count ${initial_commit}..HEAD) == 1)); then
  git checkout ${initial_commit}
else
  git checkout $(git rev-list --reverse ${initial_commit}..HEAD | tail -2 | head -1)
fi
