#!/usr/bin/env bash

# $1: which module

if [[ -z $1 ]]; then
  echo You must specify which module to make patches!
  exit 1
fi

mkdir -p $1-patches

cd $1

patches_dir=../$1-patches
hostname=$(hostname)
date=$(date +%Y%m%d)
sha1=$(git rev-parse --short HEAD)

diff -up config.def.h config.h > \
  $patches_dir/$1-config$hostname-$date-$sha1.diff

if [[ -n $(git diff) ]]; then
  git diff > \
    $patches_dir/$1-custom-$date-$sha1.diff
fi
