#!/bin/bash

MACMILLAN_DICT_URL="https://www.macmillandictionary.com/us/dictionary/american"
OXFORD_DICT_URL="https://www.lexico.com/en/definition"
CAMBRIDGE_DICT_URL="https://dictionary.cambridge.org/dictionary/english"

die() {
  echo "$@"; exit 1
}

usage() {
  cat <<EOF
Usage:
  camdict [-h|--help] [-a,--all] [-c,--cambridge] [-o,--oxford] [-P,--primary] [-C,--clipboard] [word]

Options:
  -h,--help         display this help
  -a,--all          search the word in all supported dictionaries
  -c,--cambridge    use cambridge dictionary instead, default is macmillan dictionary
  -o,--oxford       use oxford dictionary instead, default is macmillan dictionary
  -P,--primary      search word from pimary selection
  -C,--clipboard    search word from clipboard selection
  word              search word from command line argument
EOF
}

# Default dictionary
dict_urls=("$MACMILLAN_DICT_URL")

while (( ${#@} > 0 )); do
  case "$1" in
    -h|--help      ) usage; exit 0 ;;
    -a|--all       ) dict_urls=("$MACMILLAN_DICT_URL" "$OXFORD_DICT_URL" "$CAMBRIDGE_DICT_URL");;
    -c|--cambridge ) dict_urls=("$CAMBRIDGE_DICT_URL") ;;
    -o|--oxford    ) dict_urls=("$OXFORD_DICT_URL") ;;
    -P|--primary   ) [[ -z $word ]] && word=$(xclip -r -o -selection primary | tr '[:upper:]' '[:lower:]') || die "Support only one word at one time" ;;
    -C|--clipboard ) [[ -z $word ]] && word=$(xclip -r -o -selection clipboard | tr '[:upper:]' '[:lower:]') || die "Support only one word at one time" ;;
    *              ) [[ -z $word ]] && word=${1,,} || die "Support only one word at one time" ;;
  esac
  shift
done

[[ -z $word ]] && die "No word to search" 

for dict_url in "${dict_urls[@]}"; do
  qutebrowser --target tab "$dict_url/$word" &> /dev/null &
done
