#!/bin/bash

blog_dir="$(dirname "$(readlink ~/.blog)")"

if [[ -d $blog_dir/reStructuredText ]]; then
  IFS=$'\n'
  for pass in $(find -L "$blog_dir/reStructuredText" -type f -path '*.rst' -printf "%P\n"); do
    echo "${pass%%.rst}"
  done
fi
